library/urls.py
from django.urls import path


from . import views


urlpatterns = [
    path('', views.libraries, name='libraries'),
    path('home/', views.home, name='home'),
    path('library/add/', views.add_library, name='add_library'),
    path('library/<int:library_id>/', views.detail_library, name='detail_library'),
    path('library/edit/<int:library_id>/', views.edit_library, name='edit_library'),
    path('library/delete/<int:library_id>/', views.delete_library, name='delete_library'),
    path('library/<int:library_id>/books/add/', views.add_book_library, name='add_book_library'),

    path('books/', views.book_list, name='book_list'),
    path('books/borrow/<int:id>', views.borrow_book, name='borrow_book'),
    path('books/return/<int:id>', views.return_book, name='return_book'),
    path('book/', views.book, name='book'),
    path('book/add', views.add_book, name='add_book'),
    path('book/edit/<int:id>', views.edit_book, name='edit_book'),
    path('book/delete/<int:id>', views.delete_book, name='delete_book'),

    path('profile', views.profile, name='profile'),
    path('profile/edit', views.edit_profile, name='edit_profile'),

    path('group/', views.groups, name='groups'),
    path('group/add/', views.add_group, name='add_group'),
    path('group/<int:group_id>/', views.detail_group, name='detail_group'),
    path('group/edit/<int:group_id>/', views.edit_group, name='edit_group'),
    path('group/delete/<int:group_id>/', views.delete_group, name='delete_group'),
    path('group/<int:group_id>/join/', views.join_group, name='join_group'),
    path('group/<int:group_id>/leave/', views.leave_group, name='leave_group'),
    path('group/<int:group_id>/sessions/add/', views.add_session, name='add_session'),
    path('group/<int:group_id>/sessions/edit/<int:session_id>/', views.edit_session, name='edit_session'),
    path('group/<int:group_id>/sessions/delete/<int:session_id>/', views.delete_session, name='delete_session'),
    
    path('salons/', views.salons, name='salons'),
    path('salons/<int:salon_id>/', views.detail_salon, name='detail_salon'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from library import views, forms
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('library/', include('library.urls')),
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html', redirect_authenticated_user=True, form_class=forms.LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('', views.index, name='index'),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

library/models.py
from django.db import models
from django.conf import settings
from datetime import datetime, timedelta
USER = settings.AUTH_USER_MODEL
from django.utils import timezone
now = timezone.now()


# LIBRARY
class Library(models.Model):
    owner = models.ForeignKey(USER, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=80)
    city = models.CharField(max_length=80)
    address = models.CharField(max_length=80)

    def __str__(self):
        return self.name
# BOOKS


class Book(models.Model):
    library = models.ForeignKey(Library, on_delete=models.CASCADE,null=True)
    title = models.CharField(max_length=80)
    author = models.CharField(max_length=80)
    editor = models.CharField(max_length=80)
    jacket = models.ImageField(upload_to='images', default=None)  # image
    collection = models.CharField(max_length=80)
    genre = models.CharField(max_length=80)
    duration_max = models.IntegerField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return 'Title : ' + self.title + ' | Authors : ' + self.author +' | Library : ' + self.library.name


class Book_User(models.Model):
    user = models.ForeignKey(USER, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    borrowed_at = models.DateTimeField()
    returned_at = models.DateTimeField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def is_returned_date_exceeded(self):
        if(self.returned_at < now):
            return True


# FORUM


class Salon(models.Model):
    title = models.CharField(max_length=80)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class Message(models.Model):
    user = models.ForeignKey(USER, on_delete=models.SET_NULL, null=True)
    salon = models.ForeignKey(Salon, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)



# SESSION (Seance)


class Group(models.Model):
    owner = models.ForeignKey(USER, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=80)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
class User_Group(models.Model):
    user = models.ForeignKey(USER, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE, null=True)
    isActive = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Session(models.Model):
    date = models.DateField()
    hour = models.TimeField()
    group = models.ForeignKey(Group, on_delete=models.CASCADE,null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

library/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.http import HttpResponse, HttpResponseNotFound
from django.db.models import Q
from django.utils import timezone

from django.contrib import messages
from .forms import SignUpForm , BookForm, LibraryForm, Book_User , BookLibraryForm , ProfileForm, GroupForm, SessionForm, SalonForm, User
from .models import Library, Session, User_Group, Salon, Message, Group, Book, Book_User
from datetime import datetime, timedelta

def index(request):
    if request.user.is_authenticated:
        return redirect('home')
    return render(request, 'landing_page.html')

def register(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account created successfully')

            return redirect('login')
    else:
        form = SignUpForm()

    context = {'form': form}
    return render(request, 'registration/register.html', context)

def home(request):
    if request.user.is_authenticated:
        user_group = User_Group.objects.filter(user=request.user)
        groups = Group.objects.filter(user_group__in=user_group)
        sessions = Session.objects.filter(group__in=groups, date__gte=datetime.now())
        
        # get all borrowed books by the user
        borrowed_books = Book_User.objects.filter(user=request.user)
        
        context = {'sessions': sessions, 'borrowed_books': borrowed_books}
        return render(request, './home.html', context)
    return HttpResponseNotFound('<h1>Page not found</h1>')

def libraries(request):
    if request.user.is_authenticated:
        libraries = Library.objects.all().exclude(owner=request.user)
        my_libraries = Library.objects.filter(owner=request.user)

        context = {'libraries': libraries, 'myLibraries': my_libraries}

        return render(request, 'library/index.html', context)
    return HttpResponseNotFound('<h1>Page not found</h1>')

def add_library(request):
    if request.user.is_authenticated == False:
        return HttpResponseNotFound('<h1>Page not found</h1>')
    
    if request.method == 'POST':
        form = LibraryForm(request.POST)
        if form.is_valid():
            form.instance.owner = request.user
            form.save()
            messages.success(request, 'Library created successfully')

            return redirect('libraries')
    else:
        form = LibraryForm()

    context = {'form': form}
    return render(request, 'library/add.html', context)

def detail_library(request, library_id):
    if request.user.is_authenticated:
        library = Library.objects.get(id=library_id)
        books = Book.objects.filter(library=library_id)
        context = {'library': library, 'books': books}
        return render(request, 'library/detail.html', context)
    return HttpResponseNotFound('<h1>Page not found</h1>')

def edit_library(request, library_id):
    if request.user.is_authenticated:
        library = Library.objects.get(id=library_id)

        if library.owner != request.user:
            return redirect('libraries')

        if request.method == 'POST':
            form = LibraryForm(request.POST, instance=library)
            if form.is_valid():
                form.save()
                messages.success(request, 'Library updated successfully')

                return redirect('libraries')
        else:
            form = LibraryForm(instance=library)

        context = {'form': form, 'name': library.name}
        return render(request, 'library/edit.html', context)
    return HttpResponseNotFound('<h1>Page not found</h1>')

def delete_library(request, library_id):
    if request.user.is_authenticated:
        library = Library.objects.get(id=library_id)

        if library.owner != request.user:
            return redirect('libraries')

        library.delete()
        messages.success(request, 'Library deleted successfully')

        return redirect('libraries')
    return HttpResponseNotFound('<h1>Page not found</h1>')

def add_book_library(request, library_id):
    if request.user.is_authenticated:
        library = Library.objects.get(id=library_id)

        if library.owner != request.user:
            return redirect('libraries')

        if request.method == 'POST':
            form = BookLibraryForm(request.POST, request.FILES, lib_id = library_id)
            if form.is_valid():
                form.instance.library = library
                form.save()
                messages.success(request, 'Book added successfully')

                return redirect('detail_library', library_id)
        else:
            form = BookLibraryForm(lib_id = library_id)
            form.instance.library = library

        context = {'form': form, 'library': library}
        return render(request, 'library/books/add.html', context)
    return HttpResponseNotFound('<h1>Page not found</h1>')

def book(request):
    if request.user.is_authenticated :
        library_list = Library.objects.filter(owner=request.user.id)
        if(len(library_list) == 0):
            books = []
        else:
            books = []
            for lib in library_list:
                books.extend(Book.objects.filter(library = lib.id))
        
        book_user = Book_User.objects.all().prefetch_related('book__book_user_set')

        return render(request, 'book/book.html', {'books': books, 'library_list': library_list, 'book_user': book_user})
    return HttpResponseNotFound('<h1>Page not found</h1>')

def add_book(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            
            form = BookForm( request.POST,request.FILES,user_id = request.user.id  )
            if form.is_valid() and form.instance.duration_max > 0:
                form.save()
                messages.success(request, 'Book added successfully')

                return redirect('book')
        else:
            form = BookForm(user_id = request.user.id)
        
        context = {'form': form}
        return render(request, 'book/add.html',context)
    return HttpResponseNotFound('<h1>Page not found</h1>')

def edit_book(request, id):
    if request.user.is_authenticated:
        book = Book.objects.get(id=id)

        if book.library.owner == request.user:
            if request.method == 'POST':
                form = BookForm(request.POST,request.FILES,instance=book,user_id = request.user.id)
                if form.is_valid() and form.instance.duration_max > 0:
                    form.save()
                    messages.success(request, 'Book updated successfully')

                    return redirect('book')
            else:
                form = BookForm(instance=book,user_id = request.user.id)
            
            context = {'form': form}
            return render(request, 'book/edit.html',context)
    return HttpResponseNotFound('<h1>Page not found</h1>')

def delete_book(request, id):
    if request.user.is_authenticated:
        book = Book.objects.get(id=id)
        if book.library.owner == request.user:
            book.delete()
            messages.success(request, 'Book deleted successfully')

            return redirect(request.META.get('HTTP_REFERER'))
    return HttpResponseNotFound('<h1>Page not found</h1>')

def book_list(request):
    if request.user.is_authenticated:
        library_list = Library.objects.exclude(owner=request.user)
        books = []
        if(library_list.count() == 1):
            books = Book.objects.filter(library__in = library_list)
        else:
            for lib in library_list:
                books.extend(Book.objects.filter(library = lib.id))

        keyword = request.GET.get('search')
        if keyword:
          keyword = keyword.strip()
          books = books.filter(
            Q(title__icontains=keyword) |
            Q(author__icontains=keyword) |
            Q(editor__icontains=keyword) |
            Q(collection__icontains=keyword) |
            Q(genre__icontains=keyword) |
            Q(library__address__icontains=keyword) |
            Q(library__city__icontains=keyword) |
            Q(library__name__icontains=keyword)
          ).distinct()

        book_user = Book_User.objects.all().prefetch_related('book_user_set')
        return render(request, 'book/list.html', {'books': books, 'book_users': book_user})
    return HttpResponseNotFound('<h1>Page not found</h1>')

def borrow_book(request, id):
    if request.user.is_authenticated:
        book_user = Book_User()
        book = Book.objects.get(id=id)
        book_user.book = book
        book_user.user = request.user
        book_user.borrowed_at = datetime.now()
        book_user.returned_at = datetime.now() +  timedelta(days = book.duration_max)

        book_user.save()
        messages.success(request, 'Book borrowed successfully')

        return redirect(request.META.get('HTTP_REFERER'))
    return HttpResponseNotFound('<h1>Page not found</h1>')

def return_book(request, id):
    if request.user.is_authenticated:
        book_user = Book_User.objects.get(book=id)
        book_user.delete()
        messages.success(request, 'Book returned successfully')

        return redirect(request.META.get('HTTP_REFERER'))
    return HttpResponseNotFound('<h1>Page not found</h1>')

def profile(request):
    if request.user.is_authenticated:
        # user = User.objects.get(id=request.user.id)
        user = request.user
        books = Book_User.objects.filter(user = request.user.id).exclude(returned_at__lt=datetime.now())
        books_late = Book_User.objects.filter(user = request.user.id).exclude(returned_at__gt=datetime.now())
        return render(request, 'profile/index.html', {'user': user, 'books': books, 'books_late': books_late})
    return HttpResponseNotFound('<h1>Page not found</h1>')

def edit_profile(request):
    if request.user.is_authenticated:

library/templates/group/add.html
{% extends "../base.html" %}

{% block title %}Ajouter une bibliothèque{% endblock %}

{% block content %}
{% if form.errors %}
  <p>Le formulaire contient des erreurs :</p>
  <ul>
    {% for field in form %}
      {% for error in field.errors %}
        <li>{{ field.label }} : {{ error }}</li>
      {% endfor %}
    {% endfor %}
  </ul>
{% endif %}

<div class="card w-50 mx-auto">
  <div class="card-header text-center">
    <h1>Ajouter une bibliothèque</h1>
  </div>
  <div class="card-body justify-content-center">
    <form method="post">
      {% csrf_token %}
      {% for field in form %}
        <div class="form-group mb-2">
          <label for="{{ field.id_for_label }}">{{ field.label }} :</label>
          {{ field }}
        </div>
      {% endfor %}
      <div class="form-group mt-4 mb-2 text-center">
        <button type="submit" class="btn btn-primary">Ajouter</button>
      </div>
    </form>
  </div>
</div>

{% endblock %}

library/templates/group/detail.html
{% extends '../base.html' %}

{% block title %}{{ group.name }}{% endblock %}

{% block content %}

<div class="mb-3 row">
  <div class="col">
    <h1>{{ group.name }}
      {% if group.owner == user %}
        <a href="{% url 'edit_group' group.id %}" class="btn btn-warning"><i class="bi bi-pencil"></i></a>
        <a href="{% url 'delete_group' group.id %}" class="btn btn-danger"><i class="bi bi-trash"></i></a>
      {% else %}
        <a href="{% url 'leave_group' group.id %}" class="btn btn-danger"><i class="bi bi-person-dash"></i></a>
      {% endif %}
    </h1>
  </div>
</div>

<div class="card mb-3">
  <div class="card-body">
    <div class="card-text">
      <p>Nom : {{ group.name }}</p>
    </div>
  </div>
</div>

<div class="mt-5">
  <h1>Séances
    {% if group.owner == user %}
      <a href="{% url 'add_session' group.id %}" class="btn btn-success"><i class="bi bi-plus-lg"></i></a>
    {% endif %}
  </h1>

  {% if sessions|length >= 0 %}
  <div class="row row-cols-4">
    {% for session in sessions %}
      <div class="col">
          <div class="card">
              <div class="card-body">
                  <h5 class="card-title">{{ session.date|date:"d/m/Y" }}</h5>
                  <p class="card-text">À : {{ session.hour|time:"H:i" }}</p>
              </div>
              <div class="d-flex justify-content-end card-footer">
                  {% if group.owner == user %}
                    <a href="{% url 'edit_session' group.id session.id %}" class="btn btn-warning"><i class="bi bi-pencil"></i></a>
                    <a href="{% url 'delete_session' group.id session.id %}" class="btn btn-danger ms-2"><i class="bi bi-trash"></i></a>
                  {% endif %}
              </div>
          </div>
      </div>
    {% endfor %}
  </div>
  {% endif %}
</div>

{% endblock %}

library/templates/group/edit.html
{% extends "base.html" %}

{% block title %}Éditer un groupe{% endblock %}

{% block content %}
{% if form.errors %}
  <p>Le formulaire contient des erreurs :</p>
  <ul>
    {% for field in form %}
      {% for error in field.errors %}
        <li>{{ field.label }} : {{ error }}</li>
      {% endfor %}
    {% endfor %}
  </ul>
{% endif %}

<div class="card w-50 mx-auto">
  <div class="card-header text-center">
    <h1>Éditer {{ name }}</h1>
  </div>
  <div class="card-body justify-content-center">
    <form method="post">
      {% csrf_token %}
      {% for field in form %}
        <div class="form-group mb-2">
          <label for="{{ field.id_for_label }}">{{ field.label }} :</label>
          {{ field }}
        </div>
      {% endfor %}
      <div class="form-group mt-4 mb-2 text-center">
        <button type="submit" class="btn btn-primary">Sauvegarder</button>
      </div>
    </form>
  </div>
</div>

{% endblock %}

library/templates/group/index.html
{% extends '../base.html' %}

{% block title %}Groupes{% endblock %}

{% block content %}

{% if myGroups %}
    <div>
        <div class="row">
            <div class="col">
                <h1>Mes groupes
                    <a href="{% url 'add_group' %}" class="btn btn-success"><i class="bi bi-plus-lg"></i></a>
                </h1>
            </div>
        </div>

        <div class="row row-cols-4 mt-3">
            {% for group in myGroups %}
                <div class="col">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">{{ group.name }}</h5>
                            <p class="card-text">{{ group.city }}</p>
                        </div>
                        <div class="d-flex justify-content-end card-footer">
                            <a href="{% url 'detail_group' group.id %}" class="btn btn-primary"><i class="bi bi-eye"></i></a>
                            <a href="{% url 'edit_group' group.id %}" class="btn btn-warning ms-2"><i class="bi bi-pencil"></i></a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% else %}
    <a href="{% url 'add_group' %}" class="btn btn-primary">Créer mon premier groupe</a>
{% endif %}
<hr class="mt-5"/>
<div class="mt-5">
    <div class="row">
        <div class="col">
            <h1>Groupes</h1>
        </div>
    </div>

    <div class="row row-cols-4 mt-3">
        {% for group in groups %}
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ group.name }}</h5>
                        <p class="card-text">{{ group.city }}</p>
                    </div>
                    <div class="d-flex justify-content-end card-footer">
                        {% if group.user_group_set.all %}
                            <a href="{% url 'detail_group' group.id %}" class="btn btn-primary"><i class="bi bi-eye"></i></a>
                            <a href="{% url 'leave_group' group.id %}" class="btn btn-secondary ms-2"><i class="bi bi-person-dash"></i></a>
                        {% else %}
                            <a href="{% url 'join_group' group.id %}" class="btn btn-success"><i class="bi bi-person-add"></i></a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}